version: 0.2

cache:
  paths:
    - 'node_modules/**/*'
    - ~/.npm/**/*

env:
  variables:
    S3_BUCKET: 'TO-Be-Defined-By-AWSCodeBuild'

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - rm -rf node_modules package-lock.json
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Building the project...
      - npm run build
  post_build:
    commands:
      - echo Build completed!!
      - echo Uploading files to S3...
      - aws s3 sync ./dist/react-web-app s3://$S3_BUCKET --delete
