version: 0.2

cache:
  paths:
    - 'node_modules/**/*'
    - ~/.npm/**/*

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      # - rm -rf node_modules package-lock.json
      - echo Installing dependencies...
      - npm install --no-optional
  build:
    commands:
      - echo Building the project...
      - npm run build
  post_build:
    commands:
      - echo Build completed!!
